### ISSUE TITLE
Upload speed

### ISSUE THREAD

**Issue by sunilrx** [webtorrent/webtorrent-hybrid#58]
Hi,
While executing js code 
client.add(torrentId,{ path: '/path'}, function (torrent) {  
   var upload_interval = setInterval(function () {
        console.log('Upload Speed: ' + torrent.uploadSpeed);
   }, 5000);
}) 
is there any way to manage(increase) the upload speed?

**Comment by DiegoRBaquero** [comment]
In theory, it should max out the uplink.

**Comment by sunilrx** [comment]
Hi DiegoRBaquero,

But for me its very rarely touches 2 to 3MB/s, in most other case upload speed is less than 100KB/s

hoping for a solution.

**Comment by DiegoRBaquero** [comment]
Are you seeding locally (same computer)? in the LAN? Internet?

Can you show me results from http://www.speedtest.net/?

**Comment by sunilrx** [comment]
I am running the above as js in a Debian server.

**Comment by feross** [comment]
@sunilrx This is most likely an issue with your connection, or with your server's disk speed. Can you test your server speed using speedtest.net or https://www.npmjs.com/package/fast-cli ?

**Comment by brambox** [comment]
There is no such thing as the maxing connection speed with the webrtc.
The seeding over Webrtc using webtorrent taxes, insane CPU resources and the faster network speed the more CPU it will use. Eventually Nodejs or something is limiting it. It will rarely go over 20 Mbit. 
 
The crazy CPU ussage has been issue since day one and still there is no fix and this is the main reason why webtorrent has not become anything big.  
Well there is always hope someone will find a way...

**Comment by thenikin** [comment]
@brambox Hi,

I just tried to seed a torrent using webtorrent desktop (for mac) and indeed it maxed out the uplink. However, when seeding using webtorrent-hybrid seems to have a limitation around 20/30Mbit (200-300kb/s)

@feross any comment about this, what it might be happening here or where to look ? 

Thanks!

**Comment by jumpersdevice** [comment]
Did a little more testing today, fired up serveral instances of webtorrent-hybrid seeding the same torrent on the same computer and speed increased dramatically when requesting it from browser. It certainly looks like some kind of limitation now.

**Comment by feross** [comment]
> fired up serveral instances of webtorrent-hybrid seeding the same torrent on the same computer and speed increased dramatically when requesting it from browser

I think this is because the `wrtc` implementation is different from browser implementations -- currently it's following Chrome M81 -- and it's not quite the same quality, much as the maintainers there try. It's really hard to work with libwebrtc.

Perhaps we can try testing another webrtc implementation that has Node.js bindings. Does anyone have suggestions?
