### ISSUE TITLE
Error: Connection error: Ice connection failed.

### ISSUE THREAD

**Issue by L11R** [webtorrent/webtorrent-hybrid#68]
Just setup headless instance on VPS. Common seeds easily connect and download files, but WebRTC seeds download very small part (maybe 2-5 MB) and stop with error "Ice connection failed". If you wait some time, maybe 10 minutes, it retry and again downloads 2-5 MB then stops with this error again. I tried on 3 instances and MANY clients: Everywhere I get this problem.

**Comment by Lord-Protector** [comment]
@feross is it NAT problem? I can't find any docs fro rtcConfig in bittorrent-tracker project.

**Comment by Lord-Protector** [comment]
Full log after stop seeding: https://gist.github.com/Lord-Protector/a8a8a02913ac50876d1da720d0b449a3

**Comment by feross** [comment]
I'm going to blame electron-webrtc for this since it's about 1 year out of date from the latest browser implementations, but honestly this issue is stale enough that the ground truth has probably changed here.

I suggest following https://github.com/webtorrent/webtorrent-hybrid/issues/76 for our `wrtc` migration plans.
